# Starship Configuration - Jetpack + Nerd Font Symbols
# https://starship.rs/config/

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """$directory $git_branch$git_status$git_metrics$fill$nodejs$python$rust$golang$java$lua$ruby$docker_context$package $os$time $cmd_duration
$character"""

[fill]
symbol = ' '

[character]
format = "$symbol"
success_symbol = "[◎ ](bold italic bright-yellow)"
error_symbol = "[○ ](italic purple)"
vimcmd_symbol = "[■ ](italic dimmed green)"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[⭘ $user]($style) "
disabled = false
show_always = false

[directory]
home_symbol = "~"
truncation_length = 0
truncate_to_repo = false
read_only = " 󰌾"
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style)'

[cmd_duration]
format = "[ ◄ $duration ](italic white)"

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[▶](blue italic)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed white"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "󰁹"
charging_symbol = "󰂄"
discharging_symbol = "󰂃"
unknown_symbol = "󰁽"
empty_symbol = "󰂎"

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "italic dimmed yellow"

# Git - Nerd Font Symbols
[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style)"
symbol = " "
style = "italic bright-blue"

[git_commit]
tag_symbol = "  "

[git_metrics]
format = '([ +$added]($added_style))([ -$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic bright-blue"
format = "([$all_status$ahead_behind]($style))"
conflicted = " "
ahead = " ${count}"
behind = " ${count}"
diverged = "  ${ahead_count}  ${behind_count}"
untracked = " ${count}"
stashed = " ${count}"
modified = " ${count}"
staged = " ${count}"
renamed = "󰑕 ${count}"
deleted = " ${count}"

# Languages - Nerd Font Symbols
[aws]
symbol = "  "
format = " [$symbol$profile $region]($style)"
style = "bold blue"

[buf]
symbol = " "
format = " [$symbol$version $buf_version]($style)"

[bun]
symbol = " "

[c]
symbol = " "
format = " [$symbol($version(-$name))]($style)"

[cmake]
symbol = " "

[conda]
symbol = " "
format = " [$symbol$environment]($style)"

[crystal]
symbol = " "

[dart]
symbol = " "
format = " [$symbol($version)]($style)"

[deno]
symbol = " "
format = " [$symbol$version](green bold)"

[docker_context]
symbol = " "
format = " [$symbol$context]($style)"

[elixir]
symbol = " "
format = " [$symbol$version OTP $otp_version]($style)"

[elm]
symbol = " "
format = " [$symbol($version)]($style)"

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = " "

[golang]
symbol = " "
format = " [$symbol($version)]($style)"

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "
format = " [$symbol($version)]($style)"

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "
format = " [$symbol($version)]($style)"

[julia]
symbol = " "
format = " [$symbol($version)]($style)"

[kotlin]
symbol = " "

[lua]
symbol = " "
format = " [$symbol$version]($style)"
style = "bold bright-yellow"

[memory_usage]
symbol = "󰍛 "
format = " [$symbol$ram( $swap)]($style)"

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "
format = " [$symbol($version)]($style)"

[nix_shell]
symbol = " "
style = 'bold italic dimmed blue'
format = '[$symbol nix⎪$state⎪]($style) [$name](italic dimmed white)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
unknown_msg = '[◌](bold dimmed yellow)'

[nodejs]
symbol = " "
format = " [$symbol($version)](bold bright-green)"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[ocaml]
symbol = " "

[os]
disabled = false
format = "[$symbol]($style)"
style = "bold white"

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Kali = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
format = " [$symbol$version]($style)"
style = "dimmed yellow italic bold"

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "
format = " [$symbol$version( $virtualenv)]($style)"
style = "bold bright-yellow"

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "
format = " [$symbol$version]($style)"
style = "bold red"

[rust]
symbol = "󱘗 "
format = " [$symbol$version]($style)"
style = "bold red"

[scala]
symbol = " "

[status]
symbol = " "

[swift]
symbol = " "
format = " [$symbol$version]($style)"
style = "bold bright-red"

[terraform]
symbol = "󱁢 "

[zig]
symbol = " "
format = " [$symbol($version)]($style)"

[spack]
symbol = "◇ "
format = " [$symbol$environment]($style)"
